version: '3'

services:

  pg:
    image: "postgres:15.2-alpine3.17"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: orame
    ports:
      - 5460:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
