version: 3

dotenv: ['.env']

includes:
  client:
    taskfile: ./packages/client/Taskfile.yml
    dir: ./packages/client
  server:
    taskfile: ./packages/server/Taskfile.yml
    dir: ./packages/server
  cli:
    taskfile: ./packages/cli/Taskfile.yml
    dir: ./packages/cli

tasks:
  start:
    desc: Serve the app
    deps:
      - task: server:start
      - task: start:db
      - task: client:watch

  start:db:
    desc: start database
    cmds:
      - docker compose up -d

  drop:db:
    desc: drop database
    cmds:
      - docker compose down
      - docker volume rm orame_pg-data
      - task: start:db

  fix:all:
    desc: fix lint & format
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged --all

  init:
    desc: fix lint & format
    cmds:
      - rustup target add wasm32-unknown-unknown
      - cargo install cargo-watch
      - cargo install --locked trunk
      - cargo install --locked wasm-bindgen-cli
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - pnpm i; cd client; pnpm i
