version: 3

dotenv: ['.env']

includes:
  client:
    taskfile: ./client/Taskfile.yml
    dir: ./client
  server:
    taskfile: ./server/Taskfile.yml
    dir: ./server
  cli:
    taskfile: ./cli/Taskfile.yml
    dir: ./cli

tasks:
  start:
    desc: Serve the app
    deps:
      - task: server:start
      - task: start:db
      - task: client:watch

  start:db:
    desc: start database
    cmds:
      - docker compose up -d

  drop:db:
    desc: drop database
    cmds:
      - docker compose down
      - docker volume rm orame_pg-data
      - task: start:db

  fix:all:
    desc: fix lint & format
    cmds:
      - cargo clippy --fix --allow-dirty --allow-staged --all

  init:
    desc: fix lint & format
    cmds:
      - rustup target add wasm32-unknown-unknown
      - cargo install clippy
      - cargo install cargo-watch
      - cargo install --locked trunk
      - cargo install --locked wasm-bindgen-cli
      - pnpm i; cd client; pnpm i
