[package]
name = "universe_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cuid2 = "0.1.2"
rand = "0.8.5"
serde = { version = "1.0.192", features = ["derive"] }
serde_cbor = "0.11.2"
serde_json = "1.0.108"
toml = "0.8.8"
plotters = "0.3.5"
ogame_core = { path = "../ogame_core" }


