version: 3

includes:
  prisma:
    taskfile: ../prisma-client/Taskfile.yml
    dir: ../prisma-client

tasks:
  start:
    desc: serve the app
    deps:
      - task: prisma:gen
    cmds:
      - cargo watch -x run

