[package]
name = "ogame_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.190", features = ["derive"] }
thiserror = "1.0.50"
web-time = "0.2.3"
universe_gen = { path = "../universe_gen" }
